# Generated by Django 2.2.5 on 2020-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0002_auto_20200426_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='1', max_length=120),
        ),
    ]
