# Generated by Django 2.2.5 on 2020-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0005_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
