# Generated by Django 2.2.5 on 2020-04-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0007_auto_20200429_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='kind',
            new_name='title',
        ),
    ]
