# Generated by Django 2.2.5 on 2020-04-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0009_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='user',
        ),
    ]
