# Generated by Django 2.2.5 on 2020-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0010_remove_university_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='career',
            field=models.ManyToManyField(related_name='myuser', to='universityconnection.Career'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='course',
            field=models.ManyToManyField(related_name='myuser', to='universityconnection.Course'),
        ),
    ]
