# Generated by Django 2.2.5 on 2020-04-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0011_auto_20200430_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='universityconnection.MyUser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='user(profile_picture/nophoto.jpg', upload_to='users/profile_picture'),
        ),
    ]
