# Generated by Django 2.2.5 on 2020-05-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0015_auto_20200503_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
