# Generated by Django 2.2.5 on 2020-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0018_auto_20200503_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_picture/nophoto.jpg', upload_to='media/users/profile_picture'),
        ),
    ]
