# Generated by Django 2.2.5 on 2020-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0019_auto_20200503_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#1CBCF9', max_length=64),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=240),
        ),
    ]
