# Generated by Django 2.2.5 on 2020-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityconnection', '0020_auto_20200505_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_picture/nophoto.jpg', upload_to='users/profile_picture'),
        ),
    ]
